# Generated by Django 3.0.2 on 2020-02-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_step_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp1.Article'),
            preserve_default=False,
        ),
    ]
