# Generated by Django 3.0.2 on 2020-02-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_step_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='theme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.Theme'),
        ),
    ]
